# Generated by Django 4.1.5 on 2023-01-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AddField(
            model_name='file',
            name='mark',
            field=models.CharField(choices=[('new', 'новый'), ('changed', 'изменено'), ('deleted', 'удалено')], default=None, max_length=7),
            preserve_default=False,
        ),
    ]
