# Generated by Django 4.1.5 on 2023-01-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_file_options_file_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='changed',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='file',
            name='created',
            field=models.DateField(auto_created=True, default=None),
            preserve_default=False,
        ),
    ]
