# Generated by Django 4.1.5 on 2023-01-24 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_file_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='static/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py'])]),
        ),
    ]
