# Generated by Django 4.1.5 on 2023-01-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_file_changed_alter_file_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AddField(
            model_name='file',
            name='logs',
            field=models.FileField(null=True, upload_to='static/logs/'),
        ),
    ]
